name: CI

on: 
  push:
    branches:
    - master

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v1
    
    - name: Use Node.js 12
      uses: actions/setup-node@v1
      with:
        version: 12
        
    - name: npm install and build
      run: |
        npm install
        npm run build
